- index.html
> Feat: Google Analytics script

- README.md
> Update README with notes for getting started

- jobs.html
> Update jobs page with Mailchimp link

- .devcontainer/Dockerfile
- .devcontainer/requirements.txt
- Gemfile.lock
Closes #27 
Followed approach taken in https://github.com/cal-itp/mobility-marketplace/pull/352/commits/a2c059ac067c5af06b047310643cbd8e1cefdf12
> Fix: devcontainer dependencies

- _jobs/executive-assistant.md
Open to review by anyone, how does the formatting look? Tagging @angela-tran since I know she's been doing a lot of the website work lately.
> biz-dev job post

- _data/certs.yml
- _includes/certs.html
- _layouts/default.html
- _layouts/job_post.html
- index.html
- styles/base.css
Closes #6 
This PR adds a footer to the Compiler website according to the design in Figma ([desktop](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?node-id=8%3A49&t=MzUx1EjcCJdxL5In-4) and [mobile](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?node-id=309%3A1615&t=MzUx1EjcCJdxL5In-4)).
> Feat: footer

- _jobs/product-manager.md
@angela-tran I think it's easy to miss the "Apply Now" link. Would it be reasonable to style this as a button?
> update product manager role, re-open

- _jobs/test-engineer.md
This is not a real job post, and will be removed after we test the scan.
> Test: adding a test job post to trigger ChangeTower scan

- _jobs/customer-success-account-manager.md
> Fix: link to job application form

- _jobs/customer-success-account-manager.md
closes #75 
[https://deploy-preview-76--compilerla.netlify.app/jobs](https://deploy-preview-76--compilerla.netlify.app/jobs)
> feat(jobs): close Customer Success Account Manager job

- _includes/certs.html
- _layouts/default.html
- index.html
- jobs.html
- styles/base.css
> Refactor: jobs page styling

- _layouts/default.html
> Remove twitter logo/link from Footer

- .gitignore
This file is always coming up for me on this repo. Necessary for Mac OS machines.
> chore: add .DS_Store for macos

- _layouts/job_post.html
- jobs.html
> Horizontal alignment

- index.html
- jobs.html
closes #132 
This PR does NOT change the names of classes - that will happen in a future, bigger PR. This PR just fixes the font sizes on 2 pages: Home and Jobs
> Align text sizes

- _layouts/job_post.html
- about.html
- index.html
- jobs.html
- styles/base.css
requires #134 
closes #130 
- Adds CSS that declares the following: The first `row` in the `main` element with the `container-fluid` class (`main.container-fluid > .row:first-child`) has a margin-top/bottom of 144px or 104px depending on the device/window width.
- The `default.html` layout has a `<main class="container-fluid">`. So this means that whenever a new page is created, the developer _MUST_ start the page with a `<section class="row">`, in order to get the correct vertical alignment.
- Why not add the top/bottom margins to `<main class="container-fluid">` directly? Because that's not what Figma calls for, and it would create design errors on the About page.
```html
<section class="row">
<div class="col-lg-7 offset-lg-1">
</div>
</section>
```
> Vertical alignment

- about.html
- styles/base.css
> Feat: add artist credit for team illustrations

- _includes/nav.html
- _posts/2023-12-23-welcome.md
This is for https://app.clickup.com/t/86aywm4r2
The idea is to have a short and simple introduction to the blog
> Blog post: "Welcome to the Compiler blog"

- _posts/2023-12-13-gift-guide.md
> fix(blog): Eight not 8

- _jobs/software-engineer.md
* Updates _Preferred Qualifications_ based on our more recent work
* Updates _Compensation_ based on current Compiler offerings
* Updates the overall format/sections to align with the most recent [Account Manager](https://compiler.la/jobs/customer-success-account-manager) description
> Refactor: software engineer job description

- retreat.html
> Chore: update retreat redirect for Spring 2024

- _config.yml
- src/blog.html
Per https://github.com/compilerla/compiler.la/issues/175#issuecomment-2192359853
> Refactor: send the full post body in blog feed

- src/_data/team.yml
- src/about.html
> Feat: randomize team on About on page load

- src/our-work.html
> Feat: implement testimonial section of /our-work page

- src/our-work.html
Closes #206
I'm not sure if we should keep the bus animation
```
<span class="animate-bus">
</span>
```
in this section, I removed it but can put it back in if needed.
> Feat: implement top section of /our-work page

- src/our-work.html
- src/styles/base.css
> Feat: "What We've Done" - "see more projects" button

- src/_jobs/project-manager.md
> Project Manager post

- src/about.html
> Fix: typo in MDIP

- src/retreat.html
Closes #244 
Preview redirect URL: https://deploy-preview-245--compilerla.netlify.app/retreat
> chore(retreat): update redirect for Fall 2024

- src/blog.html
> Fix: remove limit on blog listing
