_layouts/default.html
_layouts/job_post.html
index.html
jobs.html
styles/base.css

Closes #36 
This PR refactors our layouts to use Bootstrap and tries to maintain the same net effect in terms of styling and spacing.
Note that the attempt to maintain styling/spacing is approximate due to time and lack of necessity -- this means there are some minor discrepancies between what's live on compiler.la vs. this branch. Since we'll be implementing more re-designs (#33), I think this is acceptable. The biggest discrepancy is just on the responsive behavior of the homepage buttons (which I think is ok):
This should be ok to merge in whenever approved -- let me know if you notice any unexpected regression!

Refactor: use Bootstrap

---

.devcontainer/devcontainer.json
_includes/job-apply-button.html
_includes/job-json.html
_jobs/associate-consultant-scheduling-coordinator.md
_jobs/creative-project-manager.md
_jobs/customer-success-account-manager.md
_jobs/executive-assistant.md
_jobs/product-manager.md
_jobs/software-engineer.md
_jobs/ux-ui-designer-researcher.md
_layouts/job_post.html
jobs.html

Closes #54 
Closes https://app.clickup.com/t/863gyj9pg
Running the preview site from UTC+4 shows the correct `America/Los_Angeles` time:
Added a test job with a current open window:
And confirmed it showed up under the "Accepting applications" heading:
The test open job:
A closed job:

Feat: explicit open/close dates for jobs

---

_includes/job-json.html
_jobs/associate-consultant-scheduling-coordinator.md
_jobs/creative-project-manager.md
_jobs/customer-success-account-manager.md
_jobs/executive-assistant.md
_jobs/product-manager.md
_jobs/software-engineer.md
_jobs/ux-ui-designer-researcher.md
_layouts/job_post.html
jobs.html

Part of #82 
Introduces a `type` variable to job post front matter. This is so job titles appear in a more consistent format, which is shown in the Figma screens for #82.
This PR also sorts jobs by title.

Refactor: improvements to job title formatting

---

_layouts/job_post.html

closes #83 
This PR aims to add the correct columns, width, margin/padding so the current Job page is easier to read.
- Apply margin and padding to the individual Job page for Desktop
- Change H1, H2 styles
- Remove the `Back to Jobs` page (b/c we don't have a Jobs menu link on the page yet)
These will come in subsequent PRs after https://github.com/compilerla/compiler.la/pull/87/ is merged

feat(job-post): add Bootstrap columns, top/bottom margin and padding

---

_layouts/job_post.html
index.html
styles.html
styles/base.css

part of #37 
part of #49 
Updates the fonts/colors/styles of the main style guide's buttons
- Override Bootstrap's CSS Variables https://getbootstrap.com/docs/5.2/components/buttons/#variables for `btn`, `btn-primary`, and `btn-outline-primary`
- Use `btn btn-primary`for `primary-btn`
- Use `btn btn-outline-primary` for `secondary-btn`
- `btn btn-primary`
- `btn btn-primary disabled`
- `btn btn-outline-primary`
- `btn btn-outline-primary disabled`
- `btn btn-primary` in focus

Refactor: Buttons + Create Style Guide page

---

jobs.html
styles/base.css

fix #102 
- Pill: Pill font is now white color, with padding of 4px/8px.
- App: Body background is now darker.
- Links: Links are green, and underline on hover.
**- Border width:** Figma calls for a very thin border, of 0.2px, but both Chrome and Firefox will only allow a border as thin as 0.5px.
**- Font weight:** I think the font weights that Figma calls for are 200 over what it actually needs to be. (Or put it another way, the code expects a font weight of 500 when Figma says 700.) I confirmed this visually. I'm not sure why this is happening. This pill looks more correct with this weight than what is on Figma.
The changes in this PR bring the page up to 100% on Axe. Currently, it's failing for color contrast on production.

Fix: Jobs Page, Pill

---

_layouts/job_post.html
jobs.html

fixes #112 
The design calls for the column-width alignment of the Jobs page and the Posting pages to be the same. They currently are not the same on Prod. This PR makes them the same:

Fix: Jobs/Posting alignment on Desktop

---

.vscode/tasks.json
Gemfile
Gemfile.lock

Related to #92 #93 
Testing out to see if the app runs fine locally and on build without the explicit `webrick` dependency.
https://github.com/github/pages-gem/issues/752 - but we use Ruby 2.7, so we shouldn't be affected by this.
Would need to get everyone to test this on their local machines, to make sure the app still runs locally for them.
Strangely, the Mobi Mart repo https://github.com/cal-itp/mobility-marketplace/pulls is having different results with the same dependabot upgrades:
Calitp.org doesn't have Webrick installed, and it was able to upgrade Jekyll just fine: https://github.com/cal-itp/calitp.org/blob/main/Gemfile

Remove webrick dependency

---

styles/base.css

The current font-weight for buttons on the live site is 600, but our Figma designs have it as 700.
This PR changes it to 700.

Fix: button font-weight

---

_layouts/job_post.html

@thekaveman noticed the button styles for active jobs is not working
#107 renamed the button styles, so we just needed to update the classes on this button

Fix: "Apply now" button style

---

Gemfile
Gemfile.lock

fixes #170 
Same bug as https://github.com/cal-itp/mobility-marketplace/issues/523
from https://github.com/jekyll/jekyll-sass-converter/issues/161

fix: fix jekyll build bug

---

jobs.html

Closes #174 
- Removes the Mailchimp link 
- Adds the new Hubspot link for the career mailing list form

Replace link for career mailing list

---

Gemfile
Gemfile.lock
_config.yml
src/_layouts/default.html

Closes #175 
Uses [`jekyll-feed`](https://github.com/jekyll/jekyll-feed) to generate (at build time) an [Atom feed](https://en.wikipedia.org/wiki/Atom_(web_standard)) of the blog posts.
The feed on the preview site is available here: [`https://deploy-preview-202--compilerla.netlify.app/blog/feed.xml`](https://deploy-preview-202--compilerla.netlify.app/blog/feed.xml)
I used a test channel in our Slack and subscribed to this feed with the Slack slash command:
```
/feed subscribe https://deploy-preview-202--compilerla.netlify.app/blog/feed.xml
```
And it showed me the latest post with a link back to the feed itself:
Based on how our other `/feed subscribe`s in Slack work, I would expect to get a public update in that test channel, that looks similar to the latest post shown above, when new …

Feat: add a blog feed

---

.github/workflows/add-to-project-issues.yml

Closes #8 
I think the only missing part for this PR is creating the `GH_PROJECTS_TOKEN` secret. I haven't been able to find a way to do this, maybe I'm missing permissions @thekaveman ? Or if you can create it from your account that works too.

Chore: add issues to project board workflow

---

src/_posts/2023-12-13-gift-guide.md
src/_posts/2023-12-23-welcome.md
src/_posts/2024-01-24-devcontainer-platform-agnostic-team.md
src/_posts/2024-03-11-transportation-round-up.md
src/_posts/2024-03-22-Civic-Tech-Career-Resources.md
src/_posts/2024-04-12-open-source-development.md
src/_posts/2024-05-17-Parental-Leave-Policy.md
src/_posts/2024-06-14-Tales-From-TCamp.md

The `categories` key in a blog post's front matter is a _list_ variable -- this PR converts the CSV strings to lists.
Among other things, this allows the feed to display multiple `category` entries correctly:
_See https://deploy-preview-210--compilerla.netlify.app/blog/feed.xml_
```xml
<entry>
<title type="html">
How to support a platform-agnostic engineering team with VS Code Dev Containers
</title>
...
<category term="compiler"/>
<category term="engineering"/>
...
</entry>
```
Whereas before this PR, they were parsed incorrectly (extra comma in `compiler`):
_See https://compiler.la/blog/feed.xml_
```xml
<entry>
<title type="html">
How to support a platform-agnostic engineering team with VS Code Dev Containers
</title>
...
<category term="compiler,"/>
<category term="engineering"/>
... …
```

Fix: convert blog categories to yaml list

---

src/_includes/ready-to-work.html
src/about.html
src/our-work.html

Feat: implement "Ready to work together?" section of /our-work page

---

src/_data/featured_work.yml
src/our-work.html
src/styles/base.css

Part of #212 
This PR implements the "What We've Done" section with just the first two cards.
| Desktop non-image card | Mobile non-image card |
| --- | --- |
| <img src="https://github.com/compilerla/compiler.la/assets/25497886/72a39611-da59-43a7-9d31-d008c55e2d77" width="300"> | <img src="https://github.com/compilerla/compiler.la/assets/25497886/50365d14-48e2-4c30-9a49-f6a95aeae63b" width="300"> |

Feat: "What We've Done" section - first two cards

---

src/_data/featured_work.yml
src/our-work.html
src/styles/base.css

Part of #212
This PR adds the last two cards to the "What We've Done" section.
The `min-height` styles for card content alignment needed to be tweaked a little bit so that the "description" paragraphs would also be aligned as shown in Figma.
| Before tweaks in 2764070baa23d149d617ce6b8f04a81cdb535624 | After 2764070baa23d149d617ce6b8f04a81cdb535624 | Figma |
| --- | --- | --- |
| ![image](https://github.com/compilerla/compiler.la/assets/25497886/42d17c3f-7d05-4b34-a52a-e9493c050039) | ![image](https://github.com/compilerla/compiler.la/assets/25497886/b381f164-adc0-4e92-8e26-bbd3cef991cc) | ![image](https://github.com/compilerla/compiler.la/assets/25497886/208d425c-3404-4825-b1f8-869b6a14a037) |
Builds off the branch for https://github.com/compilerla/compiler.la/pull/224

Feat: "What We've Done" - last two cards

---

src/our-work.html

Closes #225 
The problem was just some missing `<div class="row">`s. They were causing some sections to not take up the full width that they should. This matches how the About page lays out its sections.
| Before | After |
| --- | --- |
| ![image](https://github.com/compilerla/compiler.la/assets/25497886/9e7ebeac-781f-45d6-a7c5-2c7d2ce1dd6f) |  ![image](https://github.com/compilerla/compiler.la/assets/25497886/9b33168d-7566-4083-bce2-d4d60e49d0cf) |

Fix: missing rows cause extra spacing

---

src/retreat.html

Closes #274 
In `src/retreat.html` 
Update the redirect link for the new Fall 2025 Retreat Guide

Update Redirect link for ClickUp
